# Generated by Django 2.2.5 on 2019-12-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='usn',
            new_name='USN',
        ),
    ]
